### ISSUE TITLE
"ideas.home.title" remains in the Applications panel in a Subwiki after uninstalling

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-ideas#29]
Preconditions: Have at least a subwiki created

Steps to reproduce:

1. Install Ideas on farm from the main wiki
2. Get Trial license
3. Create some ideas on the main wiki and on a subwiki
4. Uninstall the Ideas app from the farm

Expected results: The app is uninstalled and disappears from the Application panel.

Actual results: The app is uninstalled but it remains in the Application panel as "ideas.home.title"

Environment: Windows 10, XWiki 10.11.6 with MySQL 5.7 and Chrome 73, Ideas Application (Pro) 1.11.8

![IdeasApplicationsSubwiki](https://user-images.githubusercontent.com/40691112/56420779-01754080-62a8-11e9-8d37-3d7c486ec870.jpg)
![IdeasOnMain](https://user-images.githubusercontent.com/40691112/56420794-1c47b500-62a8-11e9-8ca2-745cfa367acc.jpg)

**Comment by acotiuga** [comment]
The second image could be used in a separate issue that needs to be discussed: Should the homepage of an application be removed if there are children data pages created. In this case, should the `Ideas.Webhome` be deleted if there is content in the `Ideas` location? This behavior doesn't affect only the Ideas application, but all the XWiki applications.
