### ISSUE TITLE
Ideas cannot be voted from livetable - 'Error while operating Ideas'

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-ideas#38]
STEPS TO REPRODUCE

1. Create an idea entry
2. On Ideas livetable, try to vote it from the 'Yes/No' columns

EXPECTED RESULTS

The votes are recorded successfully.

ACTUAL RESULTS

An error message is displayed on the bottom of the page and the idea cannot be voted:
`Error while operating Ideas`

Environment: Windows 10 Pro 64 bit, Chrome 79, Edge 79, using a local instance XWiki 11.10.3 on PostgreSQL 12

![Error_while_voting_ideas](https://user-images.githubusercontent.com/32512703/74517923-b48be600-4f1b-11ea-8c5d-2992478a90b5.jpg)

**Comment by oanalavinia** [comment]
Tested with XWiki 11.10.3, 11.10.4 and 9.11 and I couldn't reproduce.
